# 01 Data Collection

Collect Statcast data using pybaseball and save raw files.

In [1]:
import pandas as pd
# import numpy as np
import sys
from pathlib import Path

# Make sure notebook can import src/
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

/Users/henry_tsai/Desktop/daily-mlb-hitter-forecasting

In [2]:
from src.data_loader import save_csv

In [3]:
from pybaseball import statcast

df = statcast(start_dt="2025-04-01", end_dt="2025-04-03")
df.shape

/Users/henry_tsai/Desktop/daily-mlb-hitter-forecasting/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

This is a large query, it may take a moment to complete

  0%|          | 0/3 [00:00<?, ?it/s]/Users/henry_tsai/Desktop/daily-mlb-hitter-forecasting/.venv/lib/python3.9/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 1/3 [00:03<00:06,  3.21s/it]/Users/henry_tsai/Desktop/daily-mlb-hitter-forecasting/.venv/lib/python3.9/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 2/3 [00:06<00:03,  3.27s/it]/Users/henry_tsai/Desktop/daily-mlb-hitter-forecasting/.venv/lib/python3.9/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 3/3 [00:10<00:00,  3.39s/it]

(9450, 118)

In [4]:
df.columns.tolist()

['pitch_type',
 'game_date',
 'release_speed',
 'release_pos_x',
 'release_pos_z',
 'player_name',
 'batter',
 'pitcher',
 'events',
 'description',
 'spin_dir',
 'spin_rate_deprecated',
 'break_angle_deprecated',
 'break_length_deprecated',
 'zone',
 'des',
 'game_type',
 'stand',
 'p_throws',
 'home_team',
 'away_team',
 'type',
 'hit_location',
 'bb_type',
 'balls',
 'strikes',
 'game_year',
 'pfx_x',
 'pfx_z',
 'plate_x',
 'plate_z',
 'on_3b',
 'on_2b',
 'on_1b',
 'outs_when_up',
 'inning',
 'inning_topbot',
 'hc_x',
 'hc_y',
 'tfs_deprecated',
 'tfs_zulu_deprecated',
 'umpire',
 'sv_id',
 'vx0',
 'vy0',
 'vz0',
 'ax',
 'ay',
 'az',
 'sz_top',
 'sz_bot',
 'hit_distance_sc',
 'launch_speed',
 'launch_angle',
 'effective_speed',
 'release_spin_rate',
 'release_extension',
 'game_pk',
 'fielder_2',
 'fielder_3',
 'fielder_4',
 'fielder_5',
 'fielder_6',
 'fielder_7',
 'fielder_8',
 'fielder_9',
 'release_pos_y',
 'estimated_ba_using_speedangle',
 'estimated_woba_using_speedangle',
 'woba_value',
 'woba_denom',
 'babip_value',
 'iso_value',
 'launch_speed_angle',
 'at_bat_number',
 'pitch_number',
 'pitch_name',
 'home_score',
 'away_score',
 'bat_score',
 'fld_score',
 'post_away_score',
 'post_home_score',
 'post_bat_score',
 'post_fld_score',
 'if_fielding_alignment',
 'of_fielding_alignment',
 'spin_axis',
 'delta_home_win_exp',
 'delta_run_exp',
 'bat_speed',
 'swing_length',
 'estimated_slg_using_speedangle',
 'delta_pitcher_run_exp',
 'hyper_speed',
 'home_score_diff',
 'bat_score_diff',
 'home_win_exp',
 'bat_win_exp',
 'age_pit_legacy',
 'age_bat_legacy',
 'age_pit',
 'age_bat',
 'n_thruorder_pitcher',
 'n_priorpa_thisgame_player_at_bat',
 'pitcher_days_since_prev_game',
 'batter_days_since_prev_game',
 'pitcher_days_until_next_game',
 'batter_days_until_next_game',
 'api_break_z_with_gravity',
 'api_break_x_arm',
 'api_break_x_batter_in',
 'arm_angle',
 'attack_angle',
 'attack_direction',
 'swing_path_tilt',
 'intercept_ball_minus_batter_pos_x_inches',
 'intercept_ball_minus_batter_pos_y_inches']

In [5]:
needed_cols = [
    "game_date",
    "batter",
    "pitcher",
    "player_name",
    "events",
    "description",
    "pitch_type",
    "stand",
    "p_throws",
    "launch_speed",
    "launch_angle",
    "estimated_woba_using_speedangle",
    "woba_value",
]

missing_cols = [c for c in needed_cols if c not in df.columns]

print("Missing columns:", missing_cols)

Missing columns: []

In [6]:
df_sample = df[needed_cols].copy()

print(df_sample.shape)
df_sample.head()

(9450, 13)

,game_date,batter,pitcher,player_name,events,description,pitch_type,stand,p_throws,launch_speed,launch_angle,estimated_woba_using_speedangle,woba_value
487,2025-04-03,656775,676477,"Whitlock, Garrett",strikeout,called_strike,SI,L,R,<NA>,<NA>,0.0,0.0
493,2025-04-03,656775,676477,"Whitlock, Garrett",NaN,foul,SL,L,R,97.3,-10,<NA>,<NA>
511,2025-04-03,656775,676477,"Whitlock, Garrett",NaN,ball,CH,L,R,<NA>,<NA>,<NA>,<NA>
524,2025-04-03,656775,676477,"Whitlock, Garrett",NaN,foul,SL,L,R,<NA>,<NA>,<NA>,<NA>
527,2025-04-03,656775,676477,"Whitlock, Garrett",NaN,ball,SI,L,R,<NA>,<NA>,<NA>,<NA>

In [7]:
df_sample.info()
df_sample.isna().mean().sort_values(ascending=False)

<class 'pandas.core.frame.DataFrame'>
Index: 9450 entries, 487 to 3618
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   game_date                        9450 non-null   datetime64[ns]
 1   batter                           9450 non-null   Int64
 2   pitcher                          9450 non-null   Int64
 3   player_name                      9450 non-null   object
 4   events                           2417 non-null   object
 5   description                      9450 non-null   object
 6   pitch_type                       9412 non-null   object
 7   stand                            9450 non-null   object
 8   p_throws                         9450 non-null   object
 9   launch_speed                     3017 non-null   Float64
 10  launch_angle                     3022 non-null   Int64
 11  estimated_woba_using_speedangle  2389 non-null   Float64
 12  woba_value                       2417 non-null   Float64
dtypes: Float64(3), Int64(3), datetime64[ns](1), object(6)
memory usage: 1.1+ MB

estimated_woba_using_speedangle    0.747196
events                             0.744233
woba_value                         0.744233
launch_speed                       0.680741
launch_angle                       0.680212
pitch_type                         0.004021
game_date                          0.000000
batter                             0.000000
pitcher                            0.000000
player_name                        0.000000
description                        0.000000
stand                              0.000000
p_throws                           0.000000
dtype: float64

In [8]:
output_path = PROJECT_ROOT / "data/raw/statcast_sample_2025_04_01_to_04_03.csv"

save_csv(df_sample, output_path)

print(output_path)
print("File exists:", output_path.exists())

/Users/henry_tsai/Desktop/daily-mlb-hitter-forecasting/data/raw/statcast_sample_2025_04_01_to_04_03.csv
File exists: True

In [9]:
test_load = pd.read_csv(output_path)

print(test_load.shape)
test_load.head()

(9450, 13)

,game_date,batter,pitcher,player_name,events,description,pitch_type,stand,p_throws,launch_speed,launch_angle,estimated_woba_using_speedangle,woba_value
0,2025-04-03,656775,676477,"Whitlock, Garrett",strikeout,called_strike,SI,L,R,NaN,NaN,0.0,0.0
1,2025-04-03,656775,676477,"Whitlock, Garrett",NaN,foul,SL,L,R,97.3,-10.0,NaN,NaN
2,2025-04-03,656775,676477,"Whitlock, Garrett",NaN,ball,CH,L,R,NaN,NaN,NaN,NaN
3,2025-04-03,656775,676477,"Whitlock, Garrett",NaN,foul,SL,L,R,NaN,NaN,NaN,NaN
4,2025-04-03,656775,676477,"Whitlock, Garrett",NaN,ball,SI,L,R,NaN,NaN,NaN,NaN

In [10]:
df_sample["events"].value_counts(dropna=False).head(30)

events
NaN                          7033
field_out                     991
strikeout                     601
single                        306
walk                          184
double                         89
home_run                       64
force_out                      41
grounded_into_double_play      39
hit_by_pitch                   23
field_error                    17
sac_fly                        13
intent_walk                     9
fielders_choice_out             8
sac_bunt                        7
fielders_choice                 7
truncated_pa                    6
triple                          5
double_play                     4
strikeout_double_play           3
Name: count, dtype: int64

In [11]:
df_sample["description"].value_counts(dropna=False).head(30)

description
ball                       3120
foul                       1653
hit_into_play              1591
called_strike              1565
swinging_strike            1106
blocked_ball                171
foul_tip                    104
swinging_strike_blocked      56
automatic_ball               37
hit_by_pitch                 23
foul_bunt                    16
missed_bunt                   3
bunt_foul_tip                 3
automatic_strike              1
pitchout                      1
Name: count, dtype: int64

In [12]:
df_sample[["events", "description", "launch_speed", "launch_angle", "estimated_woba_using_speedangle", "woba_value"]].head(20)

,events,description,launch_speed,launch_angle,estimated_woba_using_speedangle,woba_value
487,strikeout,called_strike,<NA>,<NA>,0.0,0.0
493,NaN,foul,97.3,-10,<NA>,<NA>
511,NaN,ball,<NA>,<NA>,<NA>,<NA>
524,NaN,foul,<NA>,<NA>,<NA>,<NA>
527,NaN,ball,<NA>,<NA>,<NA>,<NA>
545,NaN,foul,74.2,66,<NA>,<NA>
569,NaN,foul,75.3,81,<NA>,<NA>
572,NaN,called_strike,<NA>,<NA>,<NA>,<NA>
599,sac_fly,hit_into_play,90.5,39,0.022,0.0
617,NaN,blocked_ball,<NA>,<NA>,<NA>,<NA>
635,NaN,swinging_strike,<NA>,<NA>,<NA>,<NA>
655,NaN,ball,<NA>,<NA>,<NA>,<NA>
669,NaN,ball,<NA>,<NA>,<NA>,<NA>
694,field_out,hit_into_play,72.3,0,0.089,0.0
716,NaN,called_strike,<NA>,<NA>,<NA>,<NA>
739,NaN,ball,<NA>,<NA>,<NA>,<NA>
744,double,hit_into_play,102.5,20,0.522091,1.25
786,NaN,ball,<NA>,<NA>,<NA>,<NA>
810,NaN,swinging_strike,<NA>,<NA>,<NA>,<NA>
837,NaN,foul,91.1,28,<NA>,<NA>

In [13]:
df_sample[
    ["events", "description", "launch_speed", "launch_angle", "estimated_woba_using_speedangle", "woba_value"]
].isna().mean().sort_values(ascending=False)

estimated_woba_using_speedangle    0.747196
events                             0.744233
woba_value                         0.744233
launch_speed                       0.680741
launch_angle                       0.680212
description                        0.000000
dtype: float64

In [14]:
pa_df = df_sample[df_sample["events"].notna()].copy()

print(pa_df.shape)
pa_df.head()

(2417, 13)

,game_date,batter,pitcher,player_name,events,description,pitch_type,stand,p_throws,launch_speed,launch_angle,estimated_woba_using_speedangle,woba_value
487,2025-04-03,656775,676477,"Whitlock, Garrett",strikeout,called_strike,SI,L,R,<NA>,<NA>,0.0,0.0
599,2025-04-03,666185,676477,"Whitlock, Garrett",sac_fly,hit_into_play,SI,L,R,90.5,39,0.022,0.0
694,2025-04-03,602104,676477,"Whitlock, Garrett",field_out,hit_into_play,SL,R,R,72.3,0,0.089,0.0
744,2025-04-03,702616,676477,"Whitlock, Garrett",double,hit_into_play,SI,L,R,102.5,20,0.522091,1.25
534,2025-04-03,671213,621199,"Bowman, Matt",field_out,hit_into_play,FC,L,R,71.2,-37,0.064,0.0

In [15]:
pa_df["events"].value_counts().head(30)

events
field_out                    991
strikeout                    601
single                       306
walk                         184
double                        89
home_run                      64
force_out                     41
grounded_into_double_play     39
hit_by_pitch                  23
field_error                   17
sac_fly                       13
intent_walk                    9
fielders_choice_out            8
sac_bunt                       7
fielders_choice                7
truncated_pa                   6
triple                         5
double_play                    4
strikeout_double_play          3
Name: count, dtype: int64

In [16]:
pa_df[["events", "woba_value", "estimated_woba_using_speedangle"]].head(20)

         events  woba_value  estimated_woba_using_speedangle
487   strikeout         0.0                              0.0
599     sac_fly         0.0                            0.022
694   field_out         0.0                            0.089
744      double        1.25                         0.522091
534   field_out         0.0                            0.064
604      double        1.25                            0.449
686      single         0.9                            0.516
785   field_out         0.0                            0.126
830   field_out         0.0                             0.27
913   strikeout         0.0                              0.0
1014  force_out         0.0                            0.762
1088  strikeout         0.0                              0.0
1218       walk         0.7                         0.691497
884   field_out         0.0                            0.172
1228  field_out         0.0                            0.159
1354  field_out         0.0                            0.119
768   field_out         0.0                            0.133
928   field_out         0.0                            0.108
1149  strikeout         0.0                              0.0
1392     single         0.9                            0.891

In [17]:
pa_df[["woba_value", "estimated_woba_using_speedangle"]].isna().mean()

woba_value                         0.000000
estimated_woba_using_speedangle    0.011585
dtype: float64

In [18]:
pa_df["xwoba_value"] = pa_df["estimated_woba_using_speedangle"].fillna(pa_df["woba_value"])

pa_df[["events", "woba_value", "estimated_woba_using_speedangle", "xwoba_value"]].head(20)

         events  woba_value  estimated_woba_using_speedangle  xwoba_value
487   strikeout         0.0                              0.0          0.0
599     sac_fly         0.0                            0.022        0.022
694   field_out         0.0                            0.089        0.089
744      double        1.25                         0.522091     0.522091
534   field_out         0.0                            0.064        0.064
604      double        1.25                            0.449        0.449
686      single         0.9                            0.516        0.516
785   field_out         0.0                            0.126        0.126
830   field_out         0.0                             0.27         0.27
913   strikeout         0.0                              0.0          0.0
1014  force_out         0.0                            0.762        0.762
1088  strikeout         0.0                              0.0          0.0
1218       walk         0.7                         0.691497     0.691497
884   field_out         0.0                            0.172        0.172
1228  field_out         0.0                            0.159        0.159
1354  field_out         0.0                            0.119        0.119
768   field_out         0.0                            0.133        0.133
928   field_out         0.0                            0.108        0.108
1149  strikeout         0.0                              0.0          0.0
1392     single         0.9                            0.891        0.891

In [19]:
pa_df["xwoba_value"].isna().mean()

np.float64(0.0)

In [20]:
hitter_summary = (
    pa_df
    .groupby(["batter", "player_name"])
    .agg(
        PA=("events", "count"),
        xwOBA=("xwoba_value", "mean"),
        wOBA=("woba_value", "mean"),
        avg_exit_velocity=("launch_speed", "mean"),
        avg_launch_angle=("launch_angle", "mean"),
    )
    .reset_index()
    .sort_values("PA", ascending=False)
)

hitter_summary.head(20)

,batter,player_name,PA,xwOBA,wOBA,avg_exit_velocity,avg_launch_angle
83,547180,"Freeland, Kyle",4,0.27,0.0,84.766667,15.666667
1265,682998,"Rodón, Carlos",4,0.382789,0.0,94.65,46.0
1002,670770,"Eovaldi, Nathan",4,0.1395,0.0,64.0,-25.0
246,607208,"Freeland, Kyle",4,0.4625,0.675,85.95,6.25
1180,680574,"Eovaldi, Nathan",4,0.315,0.225,94.366667,4.0
645,664023,"Severino, Luis",4,0.53075,0.225,98.65,17.25
1030,671732,"Steele, Justin",4,0.191,0.225,88.125,28.25
505,656716,"Castillo, Luis",4,0.425,0.225,82.65,6.75
1244,682829,"Eovaldi, Nathan",4,0.13175,0.0,82.975,-17.0
1081,673237,"Webb, Logan",3,0.043333,0.0,83.15,-17.0
1062,672640,"Holmes, Clay",3,0.238,0.6,83.1,-29.333333
1066,672695,"Carrasco, Carlos",3,0.069,0.0,83.55,41.0
711,665487,"Allen, Logan",3,0.607261,0.233333,99.95,8.5
1090,673548,"Severino, Luis",3,0.751833,0.966667,100.1,21.0
1084,673357,"López, Pablo",3,0.007333,0.0,87.15,81.5
713,665487,"Lively, Ben",3,0.749296,0.6,79.8,4.333333
700,665155,"López, Pablo",3,0.091667,0.0,76.65,44.0
1097,676059,"Crochet, Garrett",3,0.544667,0.3,89.3,19.5
693,665052,"Holmes, Clay",3,0.42535,0.6,91.1,15.0
219,605141,"Sale, Chris",3,0.449846,0.9,97.7,27.0

In [21]:
processed_path = PROJECT_ROOT / "data/processed/pa_sample_2025_04_01_to_04_03.csv"

save_csv(pa_df, processed_path)

print(processed_path)
print("File exists:", processed_path.exists())

/Users/henry_tsai/Desktop/daily-mlb-hitter-forecasting/data/processed/pa_sample_2025_04_01_to_04_03.csv
File exists: True

In [22]:
summary_path = PROJECT_ROOT / "data/processed/hitter_summary_sample_2025_04_01_to_04_03.csv"

save_csv(hitter_summary, summary_path)

print(summary_path)
print("File exists:", summary_path.exists())

/Users/henry_tsai/Desktop/daily-mlb-hitter-forecasting/data/processed/hitter_summary_sample_2025_04_01_to_04_03.csv
File exists: True